[sssd]
services = nss, pam
domains = ldap
config_file_version = 2

[domain/ldap]
id_provider = ldap
auth_provider = ldap
ldap_uri = ldap://backend
ldap_search_base = dc=nodomain
ldap_default_bind_dn = cn=admin,dc=nodomain
ldap_default_authtok = 1
ldap_tls_reqcert = never
cache_credentials = true
